### ISSUE TITLE
Python code lacking

### ISSUE THREAD

**Issue by afzal273** [careercup/CtCI-6th-Edition-Python#20]
Can someone upload python solutions to a lot of the missing chapters/questions? Why must Java have all the solutions and not python?

**Comment by mmermerkaya** [comment]
Hi,

The Java repo has more solutions than Python because the solutions in the book are already written in Java.

All the contributors to this repo are coding the solutions in their free time, as a hobby. We're open to contributions, so feel free to solve some of the problems and create a pull request.
