### ISSUE TITLE
URLify_algo sounds wrong? What am I missing?

### ISSUE THREAD

**Issue by aderchox** [careercup/CtCI-6th-Edition-Python#263]
Isn't this wrong? What am I missing here?
https://github.com/careercup/CtCI-6th-Edition-Python/blob/6be09720f400e892d416747adde383545bc650d2/chapter_01/p03_urlify.py#L14
It will write characters on top of each other in some circumstances?
It breaks with something like this:
`print(urlify_algo("Hello World    of . . .", 20))`
Must give:
> Hello%20World%20of%20.%20.%20.

while gives:
> %

I think the true length is not needed at all, that's how I've written it in the first attempt and it seems to be working fine:
```py
def urlify_algo(string, length):
    isOnSpace = False
    index = 0
    out = ""
    for ch in string:
        if ch == " ":
            isOnSpace = True
            continue
        if isOnSpace:
            out += "%20"
            isOnSpace = False
        out += ch
        index = index + 1
    return out
```
I could've solved it with `split` and `string.join(list)` too, but I just wanted to go old-school.
Your solution might be right, because I've seen a similar solution somewhere else too, but I don't know what I'm missing :)

**Comment by brycedrennan** [comment]
The test case:
`print(urlify_algo("Hello World    of . . .", 20))`
is not a valid test case since it doesnt match the description of the inputs given in the book.
If I change the inputs to `"Hello World    of . . .                                    ", 23` then the current solutions do work.

You're correct that there are easier ways to accomplish the goal in the real world but sometimes the point of the question in an interview is to demonstrate your ability to design an algorithm that fits in the constraints given in the problem.
